---
# tasks file for collectd-client

- name: install collectd packages
  package:
    name: collectd
    state : present

- name: write configuration file
  template: 
    src : collectd.conf.j2
    dest : /etc/collectd/collectd.conf
  notify: collectd restart

